### ISSUE TITLE
Mejoras en la configuración del Gateway Service

### ISSUE THREAD

**Issue by dqmdz** [ETEREA-services/ETEREA.gateway-service#13]
# Mejoras en la configuración del Gateway Service

### 1. Centralización del nombre del servicio
- Se agregó la propiedad `app.name: gateway-service`
- Se modificó `spring.application.name` para usar la referencia `${app.name}`

### 2. Habilitación de Endpoints de Actuator
Se agregó configuración de Spring Boot Actuator:

```yaml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
```

## Beneficios
- Mayor mantenibilidad al centralizar el nombre del servicio en una sola propiedad
- Mejor monitoreo y observabilidad del servicio al exponer todos los endpoints de Actuator
- Información detallada del estado de salud del servicio

## Tipo de Cambio
- [x] Configuración
- [x] Funcionalidad
- [x] Corrección de Bug
- [x] Documentación

## Impacto
Bajo - Los cambios son a nivel de configuración y no afectan la funcionalidad core del servicio.

## Testing
- Verificar que el servicio sigue registrándose correctamente en Eureka
- Validar acceso a los endpoints de Actuator
- Comprobar que el health check muestra información detallada

/label ~configuration ~actuator ~monitoring
